### ISSUE TITLE
COPR breaks Fedora upgrade

### ISSUE THREAD

**Issue by Crote** [julekgwa/bingwallpapers#5]
When trying to upgrade Fedora, the upgrade will fail with
"Unable to upgrade to Fedora 31: Error runing transaction: package bingwallpapers-2019.03-3.noarch is already installed"
I've been getting this for every upgrade since, I believe, F28.
The package itself will work fine if you manually uninstall it before upgrading and reinstall it afterwards.
I believe it is because the RPM is not tagged with the Fedora version, so it cannot distinguish between the package for the old version and the one for the new version. The package version is currently `2019.09-3` for all builds, that should probably be `2019.09-3.fc30` for Fedora 30, and `2019.09-3.fc31` for Fedora 31.

**Comment by julekgwa** [comment]
I've added distribution tag, it should work fine from now on.
